[default]
address = "127.0.0.1"
port = 8000
workers = 16
max_blocking = 512
keep_alive = 5
ident = "PWNED"
log_level = "normal"
temp_dir = "/tmp"
cli_colors = true
secret_key = "2bChvsu8Ko4rk1jYV5xijcAN5IQVdI+wBdz9lEJRUdY="

[release.tls]
certs = "/etc/vote/ca-cert.pem"
key = "/etc/vote/ca-key.pem"

[default.databases.Vote]
url = "/etc/vote/vote.db"

min_connections = 64
max_connections = 1024
connect_timeout = 5
idle_timeout = 120
